services:
  auth_service:
    build: ./auth_service
    container_name: auth_service
    ports:
      - "8001:8001"
    volumes:
      - auth_data:/data
   

  shortening_service:
    build: ./shortening_service
    container_name: shortening_service
    ports:
      - "8000:8000"
    volumes:
      - shortener_data:/data
    depends_on:
      - auth_service


volumes:
  auth_data:
  shortener_data: