events{}

http {
    upstream shortening_service {
        server shortening_service:8000;
    }

    upstream auth_service {
        server auth_service:8001;
    }

    server {
        listen 80;
        server_name _;

        #proxy auth service under /auth/ path
        #ie. incoming /auth/users/login -> auth_service/users/login
        location /auth/ {
            proxy_pass http://auth_service/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        #proxy shortening service for all other paths
        #ie. incoming /abc123 -> shortening_service/abc123
        location / {
            proxy_pass http://shortening_service/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}