apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: url-shortener
data:
  nginx.conf: |
    events {}

    http {
        upstream shortening_service {
            server shortening-service:8000;
        }

        upstream auth_service {
            server auth-service:8001;
        }

        server {
            listen 80;
            server_name _;

            location /auth/ {
                proxy_pass http://auth_service/;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
            }

            location / {
                proxy_pass http://shortening_service/;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
            }
        }
    }
