apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: url-shortener
type: Opaque
stringData:
  JWT_SECRET: supersecretkey
  POSTGRES_DB: webservices
  POSTGRES_USER: user
  POSTGRES_PASSWORD: password
