apiVersion: apps/v1
kind: Deployment
metadata:
  name: shortening-service
  namespace: url-shortener
spec:
  replicas: 3
  selector:
    matchLabels:
      app: shortening-service
  template:
    metadata:
      labels:
        app: shortening-service
    spec:
      containers:
        - name: shortening-service
          image: winst10/shortening-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          env:
            - name: AUTH_SERVICE_URL
              value: http://auth-service:8001
            - name: DB_HOST
              value: postgres-db
            - name: DB_PORT
              value: "5432"
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: POSTGRES_DB
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: POSTGRES_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: POSTGRES_PASSWORD
          readinessProbe:
            tcpSocket:
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            tcpSocket:
              port: 8000
            initialDelaySeconds: 15
            periodSeconds: 10
