# syntax=docker/dockerfile:1 source docs.docker.com
#shortening service
FROM python:3.11-slim
WORKDIR /app
COPY requirements.txt .
RUN pip3 install --no-cache-dir -r requirements.txt
COPY . .
EXPOSE 8000
CMD ["python3", "app.py"]
